---
# tasks file users.yml

- name: Ensure MariaDB users are present.
  mysql_user:
    name: "{{ mariadb_name }}"
    host: "{{ mariadb_host | default('localhost') }}"
    password: "{{ mariadb_password }}"
    priv: "{{ mariadb_priv | default('*.*:USAGE') }}"
    state: present
  run_once: True
